homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Copenhagen

frontend:
config:
system_health:
configurator:
http:
api:
automation:

logger:
  default: warn
  logs:
    custom_components.ihc: debug

# ihc:
#   - url: !secret ihc_url
#     username: !secret ihc_username
#     password: !secret ihc_password
#     auto_setup: true

# ihcviewer:

debugpy:
  wait: true
