version: "3"
services:
  ha:
    container_name: hadev-ihcviewer
    image: "mcr.microsoft.com/devcontainers/python:3"
    volumes:
      - '..:/workspace'
    ports:
      - "8123:8123"
      - "5678:5678"
#    network_mode: host
#    privileged: true
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
