homeassistant:
  name: Home
  unit_system: metric

frontend:
config:
system_health:
configurator:
http:
api:
automation:
recorder:
  include:
    domains:
      - binary_sensor
history:
logbook:

logger:
  default: info
  logs:
    custom_components.ihcviewer: debug
    custom_components.ihc: debug

# ihc:
#   - url: !secret ihc_url
#     username: !secret ihc_username
#     password: !secret ihc_password
#     auto_setup: true

# ihcviewer:

#debugpy:
#  wait: true
